// Generated by gencpp from file mav_comm_driver/ModeConfig.msg
// DO NOT EDIT!


#ifndef MAV_COMM_DRIVER_MESSAGE_MODECONFIG_H
#define MAV_COMM_DRIVER_MESSAGE_MODECONFIG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mav_comm_driver
{
template <class ContainerAllocator>
struct ModeConfig_
{
  typedef ModeConfig_<ContainerAllocator> Type;

  ModeConfig_()
    : header()
    , mode_id(0)
    , data()  {
    }
  ModeConfig_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode_id(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mode_id_type;
  _mode_id_type mode_id;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;



  enum {
    FAULT_MODE = 0u,
    START_MODE = 8u,
    MANUAL_MODE = 16u,
    FLIGHT_MODE = 24u,
    TUNING_MODE = 56u,
  };


  typedef boost::shared_ptr< ::mav_comm_driver::ModeConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_comm_driver::ModeConfig_<ContainerAllocator> const> ConstPtr;

}; // struct ModeConfig_

typedef ::mav_comm_driver::ModeConfig_<std::allocator<void> > ModeConfig;

typedef boost::shared_ptr< ::mav_comm_driver::ModeConfig > ModeConfigPtr;
typedef boost::shared_ptr< ::mav_comm_driver::ModeConfig const> ModeConfigConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_comm_driver::ModeConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mav_comm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mav_comm_driver': ['/home/moujiawang/gcs/src/mav_comm_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_comm_driver::ModeConfig_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_comm_driver::ModeConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_comm_driver::ModeConfig_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ff71842ef7f25d484ca1c2f6bb8cd74";
  }

  static const char* value(const ::mav_comm_driver::ModeConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ff71842ef7f25d4ULL;
  static const uint64_t static_value2 = 0x84ca1c2f6bb8cd74ULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_comm_driver/ModeConfig";
  }

  static const char* value(const ::mav_comm_driver::ModeConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 mode_id\n\
uint8[] data    # must include id as header\n\
\n\
# modes\n\
uint8 FAULT_MODE = 0 # 0x00\n\
uint8 START_MODE = 8 # 0x08\n\
uint8 MANUAL_MODE = 16 # 0x10\n\
uint8 FLIGHT_MODE = 24 # 0x18\n\
uint8 TUNING_MODE = 56 # 0x38\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mav_comm_driver::ModeConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode_id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_comm_driver::ModeConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_comm_driver::ModeConfig_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode_id);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_COMM_DRIVER_MESSAGE_MODECONFIG_H
